# Generated by Django 4.2.16 on 2024-11-23 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='datetime',
            new_name='created_at',
        ),
    ]
