# Generated by Django 4.2.16 on 2024-11-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_publicacion_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='publicaciones/'),
        ),
    ]
